### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by infteract** [ssbarbee/iap-apple#1]
`(node:6684) [DEP0128] DeprecationWarning: Invalid 'main' field in 'E:\Github\*\node_modules\iap-apple\package.json' of 'dist/index.js'. Please either fix that or report it to the module author`
When running for the first time, small warning

**Comment by ssbarbee** [comment]
Hey @infteract thanks for reporting. I will do some investigation around this and probably push a patch bump! Thanks

**Comment by ssbarbee** [comment]
I pushed 2.0.5 just now. Try installing that version and let me know how it goes for you! @infteract  https://github.com/ssbarbee/iap-apple/commit/5f41ab2614c133a18ae25776f243eece823eb7ee

**Comment by infteract** [comment]
Thanks! Warning is gone
